grafana:
  image: kamon/grafana_graphite
  ports:
   - '82:80'
   - '81:81'
   - '8125:8125/udp'
   - '8126:8126'
  volumes:
   - ./data/whisper:/opt/graphite/storage/whisper
   - ./data/grafana:/opt/grafana/data
   - ./log/graphite:/opt/graphite/storage/log
